' 応用情報技術者過去問題 平成22年春期 午後問8のクラス図を再現

@startuml

class 乗客 {

}

class 操作機構 {
    + 乗車券
    + 乗車券要求()
    + 取り消し()
    + 発売()
}

class 現金機構 {
    + 現金額
    + 入金()
    + 現金額問い合わせ()
    + 収納返却()
}

class 印刷機構 {
    + 発券()
}

class 乗車券 {
    + {static} 運賃表
    + 乗車日
    + 乗車駅
    + 降車駅
    + 人数
    + 運賃
    + {static} 作成()
    + 削除()
    + 運賃問い合わせ()
    + 乗車券面編集()
    + 発券()
}



乗客 "0..*" --> "1" 操作機構
乗客 "0..*" -> "1" 現金機構

操作機構 "1" --> "1" 現金機構
操作機構 "1" --> "0..1" 乗車券

乗車券 "0..1" --> "1" 印刷機構



@enduml
