@startuml

object main

interface Print {
    ---
    {abstract} PrintWeak
    {abstract} printStrong
}

class Banner {
    - string: String
    ---
    showWithParen
    showWithAster
}

class PrintBanner extends Banner implements Print {
    ---
    PrintWeak
    printStrong
}

main --> Print


@enduml
